"""phase5_widget_data_column

Revision ID: 93898eec0e95
Revises: e891614a5df0
Create Date: 2026-04-22 11:09:31.794724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93898eec0e95'
down_revision: Union[str, Sequence[str], None] = 'e891614a5df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_messages', sa.Column('widget_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_messages', 'widget_data')
    # ### end Alembic commands ###
