"""phase3_session_state_and_messages

Revision ID: ab7adda883d3
Revises: e949355950d4
Create Date: 2026-04-21 19:26:05.188412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab7adda883d3'
down_revision: Union[str, Sequence[str], None] = 'e949355950d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create new Phase 3 tables
    op.create_table('session_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender_role', sa.String(length=10), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('widget_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_messages_id'), 'session_messages', ['id'], unique=False)
    op.create_index(op.f('ix_session_messages_session_id'), 'session_messages', ['session_id'], unique=False)

    # 2. Add session_state JSONB column to learning_sessions
    op.add_column('learning_sessions', sa.Column('session_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # 3. Drop legacy V1 tables (CASCADE required due to FK dependencies)
    # Child tables first, then parent tables
    op.execute('DROP TABLE IF EXISTS misconception_log CASCADE')
    op.execute('DROP TABLE IF EXISTS kido_mindmap_card CASCADE')
    op.execute('DROP TABLE IF EXISTS chat_message CASCADE')
    op.execute('DROP TABLE IF EXISTS session_feedback CASCADE')
    op.execute('DROP TABLE IF EXISTS session_concept CASCADE')
    op.execute('DROP TABLE IF EXISTS learning_session CASCADE')
    op.execute('DROP TABLE IF EXISTS document CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_user_email')
    op.execute('DROP TABLE IF EXISTS "user" CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_sessions', 'session_state')
    op.create_table('session_feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('feedback_json_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_session.id'], name='session_feedback_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='session_feedback_pkey'),
    sa.UniqueConstraint('session_id', name='session_feedback_session_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('session_concept',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('concept_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bkt_mastery_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('attempts_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'MASTERED', 'REVIEWING', 'SKIPPED', name='conceptstatus'), autoincrement=False, nullable=False),
    sa.Column('sub_points', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('current_point_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_point_failures', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_point_message_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kido_notes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['learning_session.id'], name='session_concept_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='session_concept_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.create_table('kido_mindmap_card',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('concept_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('kido_understanding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['session_concept.id'], name='kido_mindmap_card_concept_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_session.id'], name='kido_mindmap_card_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kido_mindmap_card_pkey')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('concept_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('user', 'kido', 'system', name='chatrole'), autoincrement=False, nullable=False),
    sa.Column('message_raw', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evaluator_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('detected_misconception', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_copied_from_slides', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('hint_requested', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('contains_math', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['session_concept.id'], name='chat_message_concept_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_session.id'], name='chat_message_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_message_pkey')
    )
    op.create_table('document',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('topics_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='document_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='document_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('learning_session',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='sessionstatus'), autoincrement=False, nullable=False),
    sa.Column('progress_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), server_default=sa.text("'Machine Learning'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name='learning_session_document_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='learning_session_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='learning_session_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('misconception_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('concept_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('misconception_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['session_concept.id'], name='misconception_log_concept_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_session.id'], name='misconception_log_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='misconception_log_pkey')
    )
    op.drop_index(op.f('ix_session_messages_session_id'), table_name='session_messages')
    op.drop_index(op.f('ix_session_messages_id'), table_name='session_messages')
    op.drop_table('session_messages')
    # ### end Alembic commands ###
