"""phase4_feedback_data_column

Revision ID: e891614a5df0
Revises: ab7adda883d3
Create Date: 2026-04-22 09:11:51.153105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e891614a5df0'
down_revision: Union[str, Sequence[str], None] = 'ab7adda883d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_sessions', sa.Column('feedback_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_sessions', 'feedback_data')
    # ### end Alembic commands ###
