(function () {
  'use strict';

  window.LearnBackWalkthroughSteps = [
    {
      id: 'dashboard_intro',
      segment: 'dashboard',
      route: 'dashboard.html',
      target: '#welcome-heading',
      title: 'Welcome to LearnBack',
      description: 'Meet Kido, your curious study partner. Choose your slides or try a demo session, then explain the ideas back in your own words. I will ask questions, respond to your explanations, and help you understand what you truly know.',
      action: 'modal',
      image: 'Components/character_dashboard.png',
      placement: 'center',
      layout: 'media-side',
      imageSize: 'large',
      blurBackdrop: true
    },
    {
      id: 'dashboard_progress_stats',
      segment: 'dashboard',
      route: 'dashboard.html',
      target: '.dashboard-banner',
      title: 'Your progress at a glance',
      description: 'This card shows your teaching streak, time spent with Kido, and your average understanding level. It gives you a quick overview of your learning progress.',
      action: 'highlight',
      placement: 'right',
      placementFallbacks: ['bottom', 'left', 'top'],
      cardSize: 'compact',
      avoidPadding: 36,
      spotlightPadding: 10
    },
    {
      id: 'dashboard_activity_calendar',
      segment: 'dashboard',
      route: 'dashboard.html',
      target: '.dashboard-calendar-wrap',
      title: 'Your teaching activity',
      description: 'This calendar tracks the days you have practiced teaching. It helps you visualize your consistency and learning rhythm over time.',
      action: 'highlight',
      placement: 'left',
      placementFallbacks: ['bottom', 'right', 'top'],
      cardSize: 'compact',
      avoidPadding: 36,
      spotlightPadding: 10
    },
    {
      id: 'dashboard_milestones',
      segment: 'dashboard',
      route: 'dashboard.html',
      target: '.dashboard-milestones',
      title: 'Milestones you unlock',
      description: 'Earn badges by building strong learning habits like showing up regularly, explaining clearly, and improving your understanding over time.',
      action: 'highlight',
      placement: 'top',
      placementFallbacks: ['right', 'left', 'bottom'],
      cardSize: 'compact',
      avoidPadding: 36,
      spotlightPadding: 10
    },
    {
      id: 'dashboard_start_session',
      segment: 'dashboard',
      route: 'dashboard.html',
      target: '#btn-start-session',
      title: 'Start teaching',
      description: 'Begin your learning session here. Upload your slides or use demo content to start teaching Kido.',
      action: 'pulse',
      placement: 'right',
      placementFallbacks: ['bottom', 'left'],
      cardSize: 'compact',
      avoidPadding: { x: 48, y: 64 },
      spotlightPadding: 12,
      placementGap: 32,
      requireAction: true,
      allowNext: true,
      endSegment: true
    },
    {
      id: 'start_session_upload_choice',
      segment: 'choice',
      route: 'start_session.html',
      target: '#btn-upload',
      title: 'Option 1: Upload your slides',
      description: 'Upload your own PDF slides when you want to learn using your actual study material.',
      action: 'highlight',
      image: 'Components/walk_upload1.png',
      placement: 'right',
      layout: 'media-side'
    },
    {
      id: 'start_session_demo_choice',
      segment: 'choice',
      route: 'start_session.html',
      target: '#btn-demo',
      title: 'Option 2: Try demo content',
      description: 'Use demo content to explore how LearnBack works. This is ideal if you want a quick experience or have reached upload limits.',
      action: 'highlight',
      image: 'Components/walk_upload2.png',
      placement: 'right',
      layout: 'media-side',
      endSegment: true
    },
    {
      id: 'upload_teaching_preview',
      segment: 'content-preview',
      route: 'upload_slides.html',
      target: '#start-session-btn',
      title: 'Today you will be teaching',
      description: 'These are the topics generated from your uploaded slides. Review them first, then start when you are ready to explain them to Kido.',
      action: 'modal',
      image: 'Components/walk_upload3.png',
      placement: 'center',
      layout: 'media-side',
      blurBackdrop: true,
      requireAction: true,
      allowNext: true,
      actionLabel: 'Click Start Session',
      endSegment: true
    },
    {
      id: 'demo_teaching_preview',
      segment: 'content-preview',
      route: 'start_session.html',
      target: '#btn-start-demo',
      title: 'Today you will be teaching',
      description: 'These are the demo topics prepared for you. Review them, then start when you are ready to begin the session.',
      action: 'modal',
      image: 'Components/walk_upload3.png',
      placement: 'center',
      layout: 'media-side',
      blurBackdrop: true,
      requireAction: true,
      allowNext: true,
      actionLabel: 'Click Start Demo Session',
      endSegment: true
    },
    {
      id: 'session_intro',
      segment: 'session',
      route: 'session.html',
      title: 'Your session is ready',
      description: 'On the right is your session dashboard. On the left is me, Kido. When you are ready, click Next and start teaching.',
      action: 'modal',
      placement: 'center',
      blurBackdrop: true,
      cardSize: 'compact',
      dismissOnNext: true
    },
    {
      id: 'session_slide_button',
      segment: 'session',
      route: 'session.html',
      target: '#btn-open-slides',
      title: 'Need a hint? Open your slides',
      description: 'Click View Slide Deck to open your slides for reference.',
      action: 'pulse',
      placement: 'top',
      placementFallbacks: ['bottom', 'left', 'right'],
      cardSize: 'pop',
      spotlightPadding: 6,
      placementGap: 16,
      triggerOn: 'message_count',
      triggerCount: 1,
      followUpId: 'session_slide_no_copy',
      dismissOnNext: true,
      skipDismissesPopup: true,
      passThrough: true
    },
    {
      id: 'session_slide_no_copy',
      segment: 'session',
      route: 'session.html',
      target: '#btn-open-slides',
      title: 'Tip: explain in your own words',
      description: 'Use slides as a reference, but do not copy from them. Explain the idea in your own words so Kido truly understands.',
      action: 'highlight',
      placement: 'top',
      placementFallbacks: ['bottom', 'left', 'right'],
      cardSize: 'pop',
      spotlightPadding: 6,
      placementGap: 16,
      hidden: true,
      dismissOnNext: true,
      skipDismissesPopup: true,
      passThrough: true
    },
    {
      id: 'session_widget_cube',
      segment: 'session',
      route: 'session.html',
      target: '#btn-request-graph',
      title: 'The yellow cube',
      description: 'When this cube glows, click it to try a quick activity Kido prepared for you.',
      action: 'pulse',
      placement: 'top',
      placementFallbacks: ['bottom', 'left', 'right'],
      cardSize: 'pop',
      spotlightPadding: 6,
      placementGap: 16,
      triggerOn: 'message_count',
      triggerCount: 2,
      dismissOnNext: true,
      skipDismissesPopup: true,
      passThrough: true
    },
    {
      id: 'session_learned_misconceptions',
      segment: 'session',
      route: 'session.html',
      target: '.dash-section--bottom',
      title: 'What Kido learned',
      description: 'Open this section to review my notes. Misconceptions highlight ideas I may have misunderstood.',
      action: 'highlight',
      placement: 'left',
      placementFallbacks: ['top', 'bottom', 'right'],
      cardSize: 'pop',
      spotlightPadding: 8,
      placementGap: 18,
      panelEdge: true,
      triggerOn: 'message_count',
      triggerCount: 4,
      dismissOnNext: true,
      skipDismissesPopup: true,
      passThrough: true
    },
    {
      id: 'session_mindmap',
      segment: 'session',
      route: 'session.html',
      target: '#btn-trigger-mindmap',
      title: 'View Kido mind map',
      description: 'Open the mind map to see how I am organizing what you have taught me.',
      action: 'highlight',
      placement: 'left',
      placementFallbacks: ['top', 'bottom', 'right'],
      cardSize: 'pop',
      spotlightPadding: 8,
      placementGap: 16,
      triggerOn: 'message_count',
      triggerCount: 5,
      dismissOnNext: true,
      skipDismissesPopup: true,
      passThrough: true
    },
    {
      id: 'session_end',
      segment: 'session',
      route: 'session.html',
      target: '#btn-header-actions',
      title: 'End session when ready',
      description: 'When you are done teaching, click End Session to get your feedback summary.',
      action: 'pulse',
      placement: 'bottom',
      placementFallbacks: ['left', 'right', 'top'],
      cardSize: 'pop',
      spotlightPadding: 8,
      placementGap: 16,
      triggerOn: 'message_count',
      triggerCount: 6,
      dismissOnNext: true,
      skipDismissesPopup: true,
      passThrough: true,
      endSegment: true
    },
    {
      id: 'feedback_mastery',
      segment: 'feedback',
      route: 'feedback.html',
      target: '#fb-mastery-card',
      mandatory: true,
      title: 'Your teaching impact',
      description: 'This section shows how much Kido improved during the session and highlights areas that may need more practice.',
      action: 'highlight',
      placement: 'bottom'
    },
    {
      id: 'feedback_misconceptions',
      segment: 'feedback',
      route: 'feedback.html',
      target: '#fb-map-toggle',
      mandatory: true,
      title: 'Review misconceptions',
      description: 'Open this section to review what Kido misunderstood and identify areas for improvement in future sessions.',
      action: 'pulse',
      placement: 'top',
      requireAction: true,
      actionLabel: 'Click View Session Misconceptions'
    },
    {
      id: 'feedback_survey',
      segment: 'feedback',
      route: 'feedback.html',
      target: '#btn-user-survey',
      mandatory: true,
      title: 'Help us improve',
      description: 'Please complete the feedback survey. Your input will help us improve LearnBack for future learners.',
      action: 'highlight',
      placement: 'top',
      requireAction: true,
      actionLabel: 'Click Complete Survey',
      endSegment: true
    }
  ];
})();
