"""Usage limits for controlled LearnBack user testing."""

MAX_ACTIVE_SESSIONS_PER_USER = 1
MAX_SESSIONS_PER_DAY = 2
MAX_MESSAGES_PER_SESSION = 25
MAX_UPLOADS_PER_USER = 2
MAX_UPLOADS_PER_DAY = 1
STALE_ACTIVE_SESSION_TIMEOUT_MINUTES = 30
MESSAGE_LIMIT_WARNING_REMAINING = 5
